# app/lib/nigeria_states.py
# Nigeria's 36 states + FCT with their primary cities.
# First city in each list is used as the Adzuna `where` param.
# Constitutional since 1996 — won't change.

NIGERIA_STATES: dict[str, list[str]] = {
    "abia":        ["Aba", "Umuahia"],
    "adamawa":     ["Yola", "Mubi"],
    "akwa ibom":   ["Uyo", "Eket"],
    "anambra":     ["Awka", "Onitsha", "Nnewi"],
    "bauchi":      ["Bauchi"],
    "bayelsa":     ["Yenagoa"],
    "benue":       ["Makurdi", "Gboko"],
    "borno":       ["Maiduguri"],
    "cross river": ["Calabar"],
    "delta":       ["Asaba", "Warri"],
    "ebonyi":      ["Abakaliki"],
    "edo":         ["Benin City", "Auchi"],
    "ekiti":       ["Ado-Ekiti"],
    "enugu":       ["Enugu", "Nsukka"],
    "fct":         ["Abuja"],
    "gombe":       ["Gombe"],
    "imo":         ["Owerri", "Orlu"],
    "jigawa":      ["Dutse", "Hadejia"],
    "kaduna":      ["Kaduna", "Zaria"],
    "kano":        ["Kano"],
    "katsina":     ["Katsina"],
    "kebbi":       ["Birnin Kebbi"],
    "kogi":        ["Lokoja"],
    "kwara":       ["Ilorin"],
    "lagos":       ["Lagos", "Ikeja", "Lekki", "Victoria Island"],
    "nasarawa":    ["Lafia"],
    "niger":       ["Minna"],
    "ogun":        ["Abeokuta", "Sagamu"],
    "ondo":        ["Akure"],
    "osun":        ["Osogbo", "Ile-Ife"],
    "oyo":         ["Ibadan", "Ogbomoso"],
    "plateau":     ["Jos"],
    "rivers":      ["Port Harcourt"],
    "sokoto":      ["Sokoto"],
    "taraba":      ["Jalingo"],
    "yobe":        ["Damaturu"],
    "zamfara":     ["Gusau"],
}